### ISSUE TITLE
Wrong equation in documentation for Gaussian RBF

### ISSUE THREAD

**Issue by MrUrq** [eljungsk/ScatteredInterpolation.jl#1]
The equation for the Gaussian distribution is currently not correct in the documentation for Available basis functions.

Currently it is:
```math
ϕ(r) = \sqrt{1 + (ɛr)^2}
```
While it should be:  
```math
ϕ(r) = e^{-(ɛr)^2}
```

**Comment by eljungsk** [comment]
Thanks, this is fixed by 8fb610a.
