### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by henry2004y** [eljungsk/ScatteredInterpolation.jl#13]
Hi,

I was trying to run the demos, but I get errors there:
```
using ScatteredInterpolation
samples = [0.0; 0.5; 0.5; 0.5; 1.0];
points = [0.0 0.0; 0.0 1.0; 1.0 0.0; 0.5 0.5; 1.0 1.0]';
itp = interpolate(Multiquadratic(), points, samples)
interpolated = evaluate(itp, [0.6; 0.6])
```

>  DimensionMismatch("matrix is not square: dimensions are (1, 5)")

**Comment by eljungsk** [comment]
Hi,

Thanks for reporting this. It is now fixed on master, and I've registered a new release.

**Comment by henry2004y** [comment]
Thanks for the quick fix! I just tried but the version number is still v0.3.4. Do I need to wait for some time until it's been approved by some package manager?

**Comment by eljungsk** [comment]
Yes, it's waiting to be merged into the General registry, which usually takes less than a day. You can see that PR at https://github.com/JuliaRegistries/General/pull/3049.
