### ISSUE TITLE
interpolate supporting subarrays?

### ISSUE THREAD

**Issue by henry2004y** [eljungsk/ScatteredInterpolation.jl#14]
Hi,

Currently the interpolate function using NearestNeighbor() only supports arrays. Is it possible for the function to support subarrays?

**Comment by eljungsk** [comment]
Hi,

Unfortunately not, as far as I can tell. The NearestNeighbors.jl package that is used under the hood does not seem to allow for creation of KD-trees of anything else than `Array`s.
The easiest solution for you would be to not feed a `view` to the interpolation, unfortunately.
