### ISSUE TITLE
Warning when installing on Julia 1.1.0

### ISSUE THREAD

**Issue by sefffal** [eljungsk/ScatteredInterpolation.jl#9]
Hello, and thank you for the very useful package.

I noticed a warning message after I updated to Julia 1.1.0.

When using the Julia package manager to:
`pkg> add ScatteredInterpolation; precompile`

The following warning is generated:
```
┌ Warning: Package ScatteredInterpolation does not have LinearAlgebra in its dependencies:
│ - If you have ScatteredInterpolation checked out for development and have
│   added LinearAlgebra as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with ScatteredInterpolation
└ Loading LinearAlgebra into ScatteredInterpolation from project dependency, future warnings for ScatteredInterpolation are suppressed.
```

From then on, whenever "using ScatteredInterpolations" is run, the same warning is generated.

**Comment by eljungsk** [comment]
Hi, I'm happy to hear that you found the package useful! 

Thanks for reporting this. I could not reproduce this on a dev'ed copy, or when tracking master, but only when using v0.3.0 from Metadata.
However, I think that it should be fixed by 53d30ee. Lets wait for v0.3.1 to be merged into Metadata.

**Comment by eljungsk** [comment]
v0.3.1 has now been merged, and gives no warning on my machine. 

Can you test on yours @sefffal?

**Comment by sefffal** [comment]
Hi, looks good to me -- I don't receive any warnings now.
Plus, the warnings were preventing Julia from caching the compiled code, so it's significantly faster for me to load the package.
Thanks!
